# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 21:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountNum', models.CharField(max_length=128, null=True)),
                ('name', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Authentication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountNum', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=128)),
                ('secureQuestion', models.CharField(max_length=512)),
                ('secureAnswer', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemNum', models.IntegerField()),
                ('name', models.CharField(max_length=512)),
                ('price', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingBag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountNum', models.CharField(max_length=128)),
                ('quantity', models.IntegerField(null=True)),
                ('item', models.ManyToManyField(to='account.Item')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountNum', models.CharField(max_length=128)),
                ('purchaseTime', models.DateTimeField(null=True)),
                ('itemList', models.ManyToManyField(to='account.Item')),
            ],
        ),
        migrations.CreateModel(
            name='WatchingHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountNum', models.CharField(max_length=128)),
                ('wacthTime', models.DateTimeField(null=True)),
                ('itemList', models.ManyToManyField(to='account.Item')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='authentication',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='account.Authentication'),
        ),
        migrations.AddField(
            model_name='account',
            name='shoppingBag',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='account.ShoppingBag'),
        ),
        migrations.AddField(
            model_name='account',
            name='shoppingHistory',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='account.ShoppingHistory'),
        ),
        migrations.AddField(
            model_name='account',
            name='watchingHistory',
            field=models.ManyToManyField(to='account.WatchingHistory'),
        ),
    ]
